### ISSUE TITLE
CSS fixes

### ISSUE THREAD

**Issue by ldrrp** [SiloCityLabs/blog#5]
- [x] Force line break on links
- [x] Make the links more prominent.
- [x] Image scaling
- [ ] Options thumbnail size? Luis working on it

Force line break on links. Make it wrap prettier.
![image](https://user-images.githubusercontent.com/1850819/59931858-e643c000-9413-11e9-807b-afa57e7dba97.png)

Make the links more prominent.
![image](https://user-images.githubusercontent.com/1850819/59931774-c01e2000-9413-11e9-933b-29e21a0d76e0.png)

**Comment by maave0** [comment]
URL fixed with break-all

![image](https://user-images.githubusercontent.com/1850819/59955746-1dd55b00-945a-11e9-9af2-bee1b130cfc7.png)

**Comment by maave0** [comment]
link wrapping test case #1. I've re-added the long link for testing. Nobody will ever care about this post again since it was a temporary sale
https://silocitylabs.com/post/2018/12/27/home-hub-sale/

link wrapping test case #2. There's a long chunk of text that's a link
https://silocitylabs.com/post/2019/05/29/phone-case-gamepad-usb-c-version/

**Comment by maave0** [comment]
image scaling test case. It works now :woman_shrugging:
https://silocitylabs.com/post/2018/09/18/infinite-free-small-storage-for-electronics/
